---
env:
  global:
    - PATH=/snap/bin:$PATH
jobs:
  include:
    - &test
      stage: test
      language: python
      python: "2.7"
      cache: pip
      dist: xenial
      sudo: required
      install:
        - pip install ansible
        - pip install molecule
        - .travis-scripts/ci-setup.sh
        - sudo lxc list
        - cp -R /home/travis/.ssh $TRAVIS_BUILD_DIR
      script:
        - sudo molecule --debug test

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
