---
jobs:
  include:
    - &test
      stage: test
      language: python
      python: "2.7"
      cache: pip
      dist: xenial
      sudo: required
      install:
        - pip install ansible
        - pip install molecule
        - sudo apt install snapd -y
        - sudo snap install lxd
        - sudo lxd init --auto
      script:
        - molecule test

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
