---
env:
  global:
    - PATH=/snap/bin:$PATH
jobs:
  include:
    - &test
      stage: test
      language: python
      python: "2.7"
      cache: pip
      dist: xenial
      sudo: required
      install:
        - .travis-scripts/ci-setup.sh
      script:
        - sudo env "PATH=$PATH" molecule --debug test

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
