---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 216000  # 24 hours
    # only if not xenial, because we will update apt's cache for xenial later
  when: ansible_os_family == 'Debian' and ansible_distribution_version is version('16.04', '!=')

- name: Install LXD
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - lxd
    - lxd-client
  when: (ansible_os_family == 'Debian' and ansible_distribution_version is version('16.04','>')) or ansible_os_family != 'Debian'

- name: Enable backports
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian' and ansible_distribution_version is version('16.04', '=')

- name: Install LXD (from backports)
  # this is necessary on xenial to get LXD 3 LTS rather than 2 LTS
  apt:
    name: "{{ item }}"
    state: latest
    default_release: xenial-backports
  with_items:
    - lxd
    - lxd-client
  when: ansible_os_family == 'Debian' and ansible_distribution_version is version('16.04', '=')
  tags:
    # yes I do want latest because an older version is already installed
    - skip_ansible_lint

- name: Create lxd-role dir
  file:
    path: /usr/share/lxd-role
    state: directory

- name: Generate LXD preseed file
  template:
    src: preseed.yml.j2
    dest: /usr/share/lxd-role/preseed.yml
    mode: 0600
    owner: root
    group: root
  notify: init LXD
